name: DBH
on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run check
  deploy:
    needs: check
    runs-on: self-hosted
    steps:
      - name: Checkout
        working-directory: /home/container/bot
        run: |
          git init
          git remote set-url origin $REPO_URL || git remote add origin $REPO_URL
          git fetch
          git reset --hard origin/deploy
        env:
          REPO_URL: ${{ github.event.repository.html_url }}
      - working-directory: /home/container/bot
        run: npm ci --omit=dev
      - working-directory: /home/container/bot
        run: npm run clean && npm run build
      - working-directory: /home/container/bot
        run: npm run pm2:start
