name: DBH
on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set env
        run: echo "REPO_URL=${{ github.repositoryUrl }}" >> $GITHUB_ENV
      - name: Git pull
        working-directory: /home/container/bot
        run: |
          git init
          git set-url origin $REPO_URL || git remote add origin $REPO_URL
          git fetch
          git reset --hard origin/deploy
      - working-directory: /home/container/bot
        run: npm ci
      - working-directory: /home/container/bot
        run: npm run clean && npm run build
      - working-directory: /home/container/bot
        run: npm run pm2:start
