name: DBH
on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]
  workflow_dispatch:
jobs:
  check-and-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run check
      - run: npm run clean && npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: out
          path: out
  deploy:
    needs: check-and-compile
    runs-on: self-hosted
    steps:
      - name: Checkout
        working-directory: /home/container/bot
        run: |
          git init
          git remote set-url origin $REPO_URL || git remote add origin $REPO_URL
          git fetch origin deploy
          git reset --hard origin/deploy
          git clean -fd
        env:
          REPO_URL: ${{ github.event.repository.html_url }}
      - working-directory: /home/container/bot
        run: |
          npm ci --omit=dev
          npm run clean
      - uses: actions/download-artifact@v4
        with:
          path: /home/container/bot/out
          name: out
      - working-directory: /home/container/bot
        run: npm run pm2:start
