name: DBH
on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Git pull
        working-directory: /home/container/bot
        run: |
          git fetch
          git reset --hard origin/deploy
      - working-directory: /home/container/bot
        run: npm ci
      - working-directory: /home/container/bot
        run: npm run clean && npm run build
      - working-directory: /home/container/bot
        run: npm run pm2:restart
