name: DBH
on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        working-directory: /home/container/bot
        run: |
          git init
          git remote set-url origin $REPO_URL || git remote add origin $REPO_URL
          git fetch
          git reset --hard origin/deploy
        env:
          REPO_URL: ${{ github.event.repository.html_url }}
      - working-directory: /home/container/bot
        run: npm ci
      - working-directory: /home/container/bot
        run: npm run check
      - working-directory: /home/container/bot
        run: npm run clean && npm run build
      - working-directory: /home/container/bot
        run: npm run pm2:start
